package com.andreast.taskstodo.presentation.theme

import androidx.compose.ui.graphics.Color

// primary =,
// onPrimary =,
// primaryContainer =,
// onPrimaryContainer =,
// inversePrimary =,
// secondary =,
// onSecondary =,
// secondaryContainer =,
// onSecondaryContainer =,
// tertiary =,
// onTertiary =,
// tertiaryContainer =,
// onTertiaryContainer =,
val backgroundLight = Color(0xFFFEFEFE)
val onBackgroundLight = Color(0xFF141414)
val surfaceLight = Color(0xFFEDF2F2)
// onSurface =,
// surfaceVariant =,
// onSurfaceVariant =,
// surfaceTint =,
// inverseSurface =,
// inverseOnSurface =,
// error =,
// onError =,
// errorContainer =,
// onErrorContainer =,
val outlineLight = Color(0xFF1D1D1D)
// outlineVariant =,
// scrim =,
// surfaceBright =,
// surfaceContainer =,
// surfaceContainerHigh =,
// surfaceContainerHighest =,
// surfaceContainerLow =,
// surfaceContainerLowest =,
// surfaceDim =

// primary =,
// onPrimary =,
// primaryContainer =,
// onPrimaryContainer =,
// inversePrimary =,
// secondary =,
// onSecondary =,
// secondaryContainer =,
// onSecondaryContainer =,
// tertiary =,
// onTertiary =,
// tertiaryContainer =,
// onTertiaryContainer =,
val backgroundDark = Color(0xFF141414)
val onBackgroundDark = Color(0xFFC5C5C5)
val surfaceDark = Color(0xFF1F1F1F)
// onSurface =,
// surfaceVariant =,
// onSurfaceVariant =,
// surfaceTint =,
// inverseSurface =,
// inverseOnSurface =,
// error =,
// onError =,
// errorContainer =,
// onErrorContainer =,
val outlineDark = Color(0xFF767676)
// outlineVariant =,
// scrim =,
// surfaceBright =,
// surfaceContainer =,
// surfaceContainerHigh =,
// surfaceContainerHighest =,
// surfaceContainerLow =,
// surfaceContainerLowest =,
// surfaceDim =
